CREATE TABLE `Products` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(250) NOT NULL,
    `Description` VARCHAR(10000),
    `Category` VARCHAR(250) NOT NULL,
    `ImageUrl` VARCHAR(2500),
    `Price` DECIMAL(18,2),
    `CreatedAt` DATETIME,
    PRIMARY KEY (`Id`)
);

CREATE TABLE `Users` (
    `Id` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(250) NOT NULL,
    `Email` VARCHAR(250) NOT NULL,
    `Password` VARCHAR(1000) NOT NULL,
    `Address` VARCHAR(1000),
    `PhoneNumber` VARCHAR(20),
    `CreatedAt` DATETIME,
    `UpdatedAt` DATETIME,
    PRIMARY KEY (`Id`),
    UNIQUE INDEX `IX_Users_Email` (`Email`)
);

-- Inserção de 100 produtos nas categorias Bebidas, Pratos e Doces
INSERT INTO `Products` (`Name`, `Description`, `Category`, `ImageUrl`, `Price`, `CreatedAt`) VALUES
-- Bebidas (30 produtos)
('Refrigerante Cola', 'Refrigerante sabor cola tradicional', 'Bebidas', NULL, 5.99, NOW()),
('Suco de Laranja Natural', 'Suco fresco de laranja espremido na hora', 'Bebidas', NULL, 8.50, NOW()),
('Água Mineral', 'Água mineral sem gás 500ml', 'Bebidas', NULL, 3.00, NOW()),
('Cerveja Pilsen', 'Cerveja tipo pilsen 350ml', 'Bebidas', NULL, 6.90, NOW()),
('Café Expresso', 'Café expresso tradicional', 'Bebidas', NULL, 4.50, NOW()),
('Chá Verde', 'Chá verde natural com limão', 'Bebidas', NULL, 7.00, NOW()),
('Vinho Tinto Seco', 'Vinho tinto seco da serra gaúcha', 'Bebidas', NULL, 45.00, NOW()),
('Capuccino', 'Capuccino cremoso com canela', 'Bebidas', NULL, 9.90, NOW()),
('Milkshake de Chocolate', 'Milkshake cremoso de chocolate', 'Bebidas', NULL, 12.50, NOW()),
('Caipirinha de Limão', 'Bebida tradicional com cachaça, limão e açúcar', 'Bebidas', NULL, 15.00, NOW()),
('Água de Coco', 'Água de coco natural', 'Bebidas', NULL, 6.50, NOW()),
('Suco de Abacaxi com Hortelã', 'Suco refrescante de abacaxi com hortelã', 'Bebidas', NULL, 9.00, NOW()),
('Cerveja Artesanal IPA', 'Cerveja artesanal tipo India Pale Ale', 'Bebidas', NULL, 18.90, NOW()),
('Espresso Duplo', 'Café espresso duplo intenso', 'Bebidas', NULL, 6.00, NOW()),
('Chá de Camomila', 'Chá calmante de camomila', 'Bebidas', NULL, 5.50, NOW()),
('Smoothie de Morango', 'Smoothie cremoso de morango com iogurte', 'Bebidas', NULL, 11.90, NOW()),
('Whisky 12 anos', 'Whisky envelhecido 12 anos', 'Bebidas', NULL, 120.00, NOW()),
('Limonada Suíça', 'Limonada refrescante com gás', 'Bebidas', NULL, 8.00, NOW()),
('Suco de Uva Integral', 'Suco de uva 100% integral', 'Bebidas', NULL, 7.50, NOW()),
('Cerveja Stout', 'Cerveja escura tipo stout', 'Bebidas', NULL, 14.90, NOW()),
('Mojito', 'Coquetel de rum, hortelã, limão e água com gás', 'Bebidas', NULL, 16.00, NOW()),
('Café com Leite', 'Café com leite tradicional', 'Bebidas', NULL, 5.00, NOW()),
('Chá Preto com Limão', 'Chá preto com toque de limão', 'Bebidas', NULL, 6.00, NOW()),
('Suco de Maracujá', 'Suco natural de maracujá', 'Bebidas', NULL, 8.90, NOW()),
('Gin Tônica', 'Coquetel de gin com água tônica', 'Bebidas', NULL, 22.00, NOW()),
('Refrigerante Guaraná', 'Refrigerante sabor guaraná', 'Bebidas', NULL, 5.99, NOW()),
('Café Gelado', 'Café gelado com leite e cubos de café', 'Bebidas', NULL, 10.50, NOW()),
('Chá de Frutas Vermelhas', 'Chá aromático de frutas vermelhas', 'Bebidas', NULL, 7.50, NOW()),
('Suco de Manga', 'Suco natural de manga', 'Bebidas', NULL, 8.00, NOW()),
('Cerveja Weiss', 'Cerveja de trigo tipo weiss', 'Bebidas', NULL, 16.90, NOW()),

-- Pratos (40 produtos)
('Feijoada Completa', 'Feijoada tradicional com acompanhamentos', 'Pratos', NULL, 35.90, NOW()),
('Strogonoff de Frango', 'Strogonoff de frango com arroz e batata palha', 'Pratos', NULL, 28.50, NOW()),
('Pizza Margherita', 'Pizza com molho de tomate, mussarela e manjericão', 'Pratos', NULL, 42.00, NOW()),
('Filé Mignon com Fritas', 'Filé mignon grelhado com batatas fritas', 'Pratos', NULL, 49.90, NOW()),
('Lasanha à Bolonhesa', 'Lasanha com molho bolonhesa e queijo', 'Pratos', NULL, 32.00, NOW()),
('Moqueca de Peixe', 'Moqueca tradicional de peixe com arroz', 'Pratos', NULL, 38.50, NOW()),
('Risoto de Funghi', 'Risoto cremoso com cogumelos funghi', 'Pratos', NULL, 36.00, NOW()),
('Frango à Parmegiana', 'Filé de frango empanado com molho de tomate e queijo', 'Pratos', NULL, 29.90, NOW()),
('Bife à Cavalo', 'Bife ancho com ovo frito e arroz', 'Pratos', NULL, 27.50, NOW()),
('Salada Caesar', 'Salada com alface, croutons, parmesão e molho caesar', 'Pratos', NULL, 22.00, NOW()),
('Penne ao Molho Pesto', 'Massa penne com molho pesto tradicional', 'Pratos', NULL, 25.90, NOW()),
('Bobó de Camarão', 'Bobó de camarão com arroz branco', 'Pratos', NULL, 45.00, NOW()),
('Costela no Bafo', 'Costela bovina assada lentamente', 'Pratos', NULL, 39.90, NOW()),
('Espaguete Carbonara', 'Espaguete com molho carbonara tradicional', 'Pratos', NULL, 30.00, NOW()),
('Peixe Grelhado', 'Filé de peixe grelhado com legumes', 'Pratos', NULL, 34.50, NOW()),
('Frango Grelhado', 'Filé de frango grelhado com salada', 'Pratos', NULL, 24.90, NOW()),
('Arroz de Pato', 'Arroz de pato à portuguesa', 'Pratos', NULL, 32.00, NOW()),
('Bacalhau à Brás', 'Bacalhau desfiado com ovos e batata palha', 'Pratos', NULL, 42.50, NOW()),
('Carne de Panela', 'Carne cozida com legumes e batatas', 'Pratos', NULL, 27.90, NOW()),
('Nhoque ao Sugo', 'Nhoque de batata com molho de tomate', 'Pratos', NULL, 26.00, NOW()),
('Omelete Recheado', 'Omelete recheado com queijo e presunto', 'Pratos', NULL, 18.50, NOW()),
('Picanha na Chapa', 'Picanha grelhada na chapa com farofa', 'Pratos', NULL, 52.00, NOW()),
('Sanduíche Natural', 'Sanduíche com peito de peru e vegetais', 'Pratos', NULL, 15.90, NOW()),
('Sopa de Legumes', 'Sopa caseira de legumes', 'Pratos', NULL, 12.00, NOW()),
('Tilápia Frita', 'Tilápia frita com molho tártaro', 'Pratos', NULL, 29.50, NOW()),
('X-Tudo', 'Hambúrguer completo com todos os acompanhamentos', 'Pratos', NULL, 22.90, NOW()),
('Yakissoba', 'Massa com legumes e carne no estilo japonês', 'Pratos', NULL, 28.00, NOW()),
('Ziti ao Forno', 'Massa ziti gratinada com queijos', 'Pratos', NULL, 26.50, NOW()),
('Acarajé', 'Bolinho de feijão-fradinho com vatapá e camarão', 'Pratos', NULL, 18.90, NOW()),
('Baião de Dois', 'Arroz com feijão verde, queijo coalho e carne seca', 'Pratos', NULL, 24.00, NOW()),
('Cuscuz Nordestino', 'Cuscuz com ovo, queijo e carne de sol', 'Pratos', NULL, 16.50, NOW()),
('Dobradinha', 'Prato tradicional com tripas e feijão branco', 'Pratos', NULL, 22.90, NOW()),
('Empadão Goiano', 'Empadão recheado com frango e pequi', 'Pratos', NULL, 19.00, NOW()),
('Farofa de Bacon', 'Farofa crocante com bacon', 'Pratos', NULL, 12.50, NOW()),
('Galinhada', 'Arroz com frango e açafrão', 'Pratos', NULL, 23.90, NOW()),
('Hambúrguer Artesanal', 'Hambúrguer 180g com queijo e molhos', 'Pratos', NULL, 24.00, NOW()),
('Iscas de Frango', 'Iscas de frango aceboladas', 'Pratos', NULL, 18.50, NOW()),
('Jiló com Carne Seca', 'Jiló refogado com carne seca', 'Pratos', NULL, 21.90, NOW()),
('Kibe Assado', 'Kibe assado recheado com queijo', 'Pratos', NULL, 16.00, NOW()),
('Lagosta Grelhada', 'Lagosta grelhada com manteiga de alho', 'Pratos', NULL, 89.90, NOW()),

-- Doces (30 produtos)
('Brigadeiro', 'Doce tradicional de chocolate', 'Doces', NULL, 2.50, NOW()),
('Beijinho', 'Doce de coco com leite condensado', 'Doces', NULL, 2.50, NOW()),
('Pudim de Leite', 'Pudim tradicional de leite condensado', 'Doces', NULL, 8.90, NOW()),
('Torta de Limão', 'Torta de limão com merengue', 'Doces', NULL, 12.00, NOW()),
('Bolo de Chocolate', 'Fatia de bolo de chocolate', 'Doces', NULL, 7.50, NOW()),
('Mousse de Maracujá', 'Mousse cremosa de maracujá', 'Doces', NULL, 9.00, NOW()),
('Paçoca', 'Doce de amendoim tradicional', 'Doces', NULL, 1.50, NOW()),
('Quindim', 'Doce de coco e gemas', 'Doces', NULL, 3.50, NOW()),
('Sorvete de Creme', 'Sorvete de creme tradicional', 'Doces', NULL, 6.90, NOW()),
('Cajuzinho', 'Doce de amendoim com formato de caju', 'Doces', NULL, 2.00, NOW()),
('Pavê de Chocolate', 'Pavê de chocolate com biscoito', 'Doces', NULL, 10.50, NOW()),
('Bolo de Cenoura', 'Fatia de bolo de cenoura com chocolate', 'Doces', NULL, 7.00, NOW()),
('Mousse de Chocolate', 'Mousse cremosa de chocolate', 'Doces', NULL, 8.50, NOW()),
('Doce de Leite', 'Doce de leite cremoso', 'Doces', NULL, 4.00, NOW()),
('Torta Holandesa', 'Torta de chocolate e creme', 'Doces', NULL, 13.50, NOW()),
('Bolo de Fubá', 'Fatia de bolo de fubá', 'Doces', NULL, 6.00, NOW()),
('Pé de Moleque', 'Doce de amendoim com rapadura', 'Doces', NULL, 2.50, NOW()),
('Sorvete de Morango', 'Sorvete de morango natural', 'Doces', NULL, 6.90, NOW()),
('Bem Casado', 'Doce tradicional de casamento', 'Doces', NULL, 3.00, NOW()),
('Romeu e Julieta', 'Goiabada com queijo', 'Doces', NULL, 5.50, NOW()),
('Suspiro', 'Doce de claras em ponto de suspiro', 'Doces', NULL, 1.50, NOW()),
('Trufa de Chocolate', 'Trufa de chocolate meio amargo', 'Doces', NULL, 4.50, NOW()),
('Bolo de Milho', 'Fatia de bolo de milho verde', 'Doces', NULL, 6.50, NOW()),
('Canjica', 'Doce de milho branco com leite condensado', 'Doces', NULL, 7.00, NOW()),
('Cocada', 'Doce de coco tradicional', 'Doces', NULL, 2.00, NOW()),
('Sorvete de Flocos', 'Sorvete de creme com flocos de chocolate', 'Doces', NULL, 7.50, NOW()),
('Maria Mole', 'Doce de coco aerado', 'Doces', NULL, 3.00, NOW()),
('Torta de Maçã', 'Torta de maçã com canela', 'Doces', NULL, 11.50, NOW()),
('Bolo Red Velvet', 'Fatia de bolo red velvet', 'Doces', NULL, 9.90, NOW()),
('Alfajor', 'Biscoito recheado com doce de leite', 'Doces', NULL, 5.00, NOW());